{% set name = "tokentrim" %}
{% set version = "0.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tokentrim-{{ version }}.tar.gz
  sha256: 379e64bb0bd2d713d9e6a9142946d613249376a9234cfaad838b1b31c4d75d30

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - tiktoken >=0.4.0

test:
  imports:
    - tokentrim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Easily trim messages arrays for use with GPTs.
  home: https://github.com/KillianLucas/tokentrim
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
